"""HWP 5.x 레코드 태그 번호.

한컴이 공개한 '한글 문서 파일 형식 5.0' 문서의 HWPTAG_BEGIN(0x010 = 16) 기준.
"""

HWPTAG_BEGIN = 0x010

# DocInfo 스트림
DOCUMENT_PROPERTIES = HWPTAG_BEGIN + 0     # 16
ID_MAPPINGS = HWPTAG_BEGIN + 1             # 17
BIN_DATA = HWPTAG_BEGIN + 2                # 18
FACE_NAME = HWPTAG_BEGIN + 3               # 19
BORDER_FILL = HWPTAG_BEGIN + 4             # 20
CHAR_SHAPE = HWPTAG_BEGIN + 5              # 21
TAB_DEF = HWPTAG_BEGIN + 6                 # 22
NUMBERING = HWPTAG_BEGIN + 7               # 23
BULLET = HWPTAG_BEGIN + 8                  # 24
PARA_SHAPE = HWPTAG_BEGIN + 9              # 25
STYLE = HWPTAG_BEGIN + 10                  # 26
DOC_DATA = HWPTAG_BEGIN + 11               # 27
DISTRIBUTE_DOC_DATA = HWPTAG_BEGIN + 12    # 28
COMPATIBLE_DOCUMENT = HWPTAG_BEGIN + 14    # 30
LAYOUT_COMPATIBILITY = HWPTAG_BEGIN + 15   # 31
TRACKCHANGE = HWPTAG_BEGIN + 16            # 32

# BodyText 스트림
PARA_HEADER = HWPTAG_BEGIN + 50            # 66
PARA_TEXT = HWPTAG_BEGIN + 51              # 67
PARA_CHAR_SHAPE = HWPTAG_BEGIN + 52        # 68
PARA_LINE_SEG = HWPTAG_BEGIN + 53          # 69
PARA_RANGE_TAG = HWPTAG_BEGIN + 54         # 70
CTRL_HEADER = HWPTAG_BEGIN + 55            # 71
LIST_HEADER = HWPTAG_BEGIN + 56            # 72
PAGE_DEF = HWPTAG_BEGIN + 57               # 73
FOOTNOTE_SHAPE = HWPTAG_BEGIN + 58         # 74
PAGE_BORDER_FILL = HWPTAG_BEGIN + 59       # 75
SHAPE_COMPONENT = HWPTAG_BEGIN + 60        # 76
TABLE = HWPTAG_BEGIN + 61                  # 77
SHAPE_COMPONENT_LINE = HWPTAG_BEGIN + 62   # 78
SHAPE_COMPONENT_RECTANGLE = HWPTAG_BEGIN + 63   # 79
SHAPE_COMPONENT_ELLIPSE = HWPTAG_BEGIN + 64     # 80
SHAPE_COMPONENT_ARC = HWPTAG_BEGIN + 65         # 81
SHAPE_COMPONENT_POLYGON = HWPTAG_BEGIN + 66     # 82
SHAPE_COMPONENT_CURVE = HWPTAG_BEGIN + 67       # 83
SHAPE_COMPONENT_OLE = HWPTAG_BEGIN + 68         # 84
SHAPE_COMPONENT_PICTURE = HWPTAG_BEGIN + 69     # 85
SHAPE_COMPONENT_CONTAINER = HWPTAG_BEGIN + 70   # 86
CTRL_DATA = HWPTAG_BEGIN + 71              # 87
EQEDIT = HWPTAG_BEGIN + 72                 # 88
SHAPE_COMPONENT_TEXTART = HWPTAG_BEGIN + 74     # 90
FORM_OBJECT = HWPTAG_BEGIN + 75            # 91
MEMO_SHAPE = HWPTAG_BEGIN + 76             # 92
MEMO_LIST = HWPTAG_BEGIN + 77              # 93
CHART_DATA = HWPTAG_BEGIN + 79             # 95
VIDEO_DATA = HWPTAG_BEGIN + 82             # 98
SHAPE_COMPONENT_UNKNOWN = HWPTAG_BEGIN + 99     # 115

NAMES = {v: k for k, v in list(globals().items()) if isinstance(v, int) and k.isupper()}

# 그리기 개체 안에서 '그림'을 뜻하는 shape 종류들
PICTURE_TAGS = {SHAPE_COMPONENT_PICTURE}
